name: sos-automation-platform
region: nyc

# Backend API Service
services:
  - name: sos-backend
    github:
      repo: SynthralOS/SynthralOS-core
      branch: main
      deploy_on_push: true
    
    # Build from root to use workspace package-lock.json
    source_dir: /
    build_command: npm ci && cd backend && npm run build
    run_command: cd backend && npm start
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - can upgrade to basic-xs ($12/month) for better performance
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PORT
        value: "4000"
        scope: RUN_TIME
      
      # Frontend build-time environment variables
      - key: VITE_API_URL
        value: ""  # Will be set to backend URL after deployment
        scope: BUILD_TIME
      
      # Database (Supabase PostgreSQL)
      - key: DATABASE_URL
        value: postgresql://postgres:SynthralOS@db.qgfutvkhhsjbjthkammv.supabase.co:5432/postgres
        scope: RUN_TIME
        type: SECRET
      
      # Redis (will be created as managed database)
      - key: REDIS_URL
        value: ""  # Will be set automatically when Redis database is created
        scope: RUN_TIME
      
      # Authentication (Clerk)
      - key: CLERK_SECRET_KEY
        value: sk_test_jbeqygk5Qe4No6rwQIlk0ZeIUAgW2Z2uWg8ijy2MLA
        scope: RUN_TIME
        type: SECRET
      - key: CLERK_PUBLISHABLE_KEY
        value: pk_test_ZXRoaWNhbC1oYXJlLTc5LmNsZXJrLmFjY291bnRzLmRldiQ
        scope: RUN_TIME
      
      # AI Providers (UPDATE THESE)
      - key: OPENAI_API_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      
      # Email Service
      - key: RESEND_API_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      
      # Nango OAuth (REQUIRED - UPDATE THIS)
      - key: NANGO_SECRET_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      - key: NANGO_HOST
        value: https://api.nango.dev
        scope: RUN_TIME
      
      # Supabase (for code blob storage)
      - key: SUPABASE_URL
        value: https://qgfutvkhhsjbjthkammv.supabase.co
        scope: RUN_TIME
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZnV0dmtoaHNqYmp0aGthbW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0Mzg2MTcsImV4cCI6MjA3ODAxNDYxN30.hhNH7orytoDzR7STQi9Zu3_e2FN_-pY0Rx6oavtH0ds
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZnV0dmtoaHNqYmp0aGthbW12Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjQzODYxNywiZXhwIjoyMDc4MDE0NjE3fQ.XaJ20gARmftwE6Sqvju42D-XJEeqFryD7BWIGr6M1P8
        scope: RUN_TIME
        type: SECRET
      
      # CORS - Frontend is served from the same origin as backend
      - key: CORS_ORIGIN
        value: ""
        scope: RUN_TIME
      
      # OpenTelemetry (Optional)
      - key: OTEL_ENABLED
        value: "false"
        scope: RUN_TIME
      - key: OTEL_SERVICE_NAME
        value: sos-backend
        scope: RUN_TIME
      - key: OTEL_SERVICE_VERSION
        value: "1.0.0"
        scope: RUN_TIME
      
      # PostHog Analytics (Optional)
      - key: POSTHOG_API_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      - key: POSTHOG_HOST
        value: https://app.posthog.com
        scope: RUN_TIME
      
      # RudderStack (Optional)
      - key: RUDDERSTACK_WRITE_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      - key: RUDDERSTACK_DATA_PLANE_URL
        value: https://hosted.rudderlabs.com
        scope: RUN_TIME
      
      # StackStorm (Optional)
      - key: STACKSTORM_ENABLED
        value: "false"
        scope: RUN_TIME
      - key: STACKSTORM_API_URL
        value: ""
        scope: RUN_TIME
      - key: STACKSTORM_API_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      
      # JWT Secret (auto-generated)
      - key: JWT_SECRET
        value: ""
        scope: RUN_TIME
        type: SECRET
        generate_value: true
    
    # Routes
    routes:
      - path: /
    
    # HTTP port
    http_port: 4000

# Frontend Static Site (Alternative: can be served from backend)
static_sites:
  - name: sos-frontend
    github:
      repo: SynthralOS/SynthralOS-core
      branch: main
      deploy_on_push: true
    
    source_dir: /
    build_command: npm ci && cd frontend && npm run build
    output_dir: /frontend/dist
    
    # Environment variables for build
    envs:
      - key: VITE_API_URL
        value: ""  # Set this to your backend URL after deployment
        scope: BUILD_TIME
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: pk_test_ZXRoaWNhbC1oYXJlLTc5LmNsZXJrLmFjY291bnRzLmRldiQ
        scope: BUILD_TIME
    
    # Routes
    routes:
      - path: /
    
    # CORS headers (if needed)
    cors:
      allow_origins:
        - "*"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - "*"
      expose_headers:
        - "*"
      max_age: 86400

# Managed Redis Database
# Note: Redis databases are created separately in DigitalOcean
# After creating the Redis database, add the connection string to environment variables
# databases:
#   - name: sos-redis
#     engine: REDIS
#     version: "7"
#     production: false

# Note: If you prefer to serve frontend from backend (same origin), 
# you can remove the static_sites section and the backend will serve 
# the frontend from its public directory.

